/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityAction = { 'rename' : null } |
  { 'revoke' : null } |
  { 'move' : null } |
  { 'delete' : null } |
  { 'create' : null } |
  { 'share' : null } |
  { 'upload' : null } |
  { 'permissionChange' : null };
export interface ActivityEntry {
  'id' : ActivityId,
  'itemId' : bigint,
  'action' : ActivityAction,
  'owner' : Principal,
  'atNs' : bigint,
  'itemKind' : ItemKind,
  'itemName' : string,
}
export type ActivityId = bigint;
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface FileEntry {
  'id' : FileId,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : bigint,
  'size' : bigint,
  'mimeType' : string,
  'updatedAt' : bigint,
  'folderId' : FolderId,
}
export type FileId = bigint;
export interface Folder {
  'id' : FolderId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'parentId' : [] | [FolderId],
}
export interface FolderContents {
  'files' : Array<FileEntry>,
  'folders' : Array<Folder>,
}
export type FolderId = bigint;
export type ItemKind = { 'file' : null } |
  { 'folder' : null };
export type Permission = { 'edit' : null } |
  { 'readOnly' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SearchResult {
  'files' : Array<FileEntry>,
  'folders' : Array<Folder>,
}
export interface Share {
  'id' : ShareId,
  'permission' : Permission,
  'itemId' : bigint,
  'sharedBy' : Principal,
  'createdAt' : bigint,
  'sharedWith' : Principal,
  'itemKind' : ItemKind,
}
export type ShareId = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFolder' : ActorMethod<[string, [] | [FolderId]], Folder>,
  'deleteFile' : ActorMethod<[FileId], boolean>,
  'deleteFolder' : ActorMethod<[FolderId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getActivity' : ActorMethod<[bigint], Array<ActivityEntry>>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFile' : ActorMethod<[FileId], [] | [FileEntry]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFolderContents' : ActorMethod<[FolderId], FolderContents>,
  'listShares' : ActorMethod<[], Array<Share>>,
  'moveFolder' : ActorMethod<[FolderId, [] | [FolderId]], [] | [Folder]>,
  'renameFolder' : ActorMethod<[FolderId, string], [] | [Folder]>,
  'revokeShare' : ActorMethod<[ShareId], boolean>,
  'schema' : ActorMethod<[], string>,
  'searchFiles' : ActorMethod<[string], SearchResult>,
  'shareItem' : ActorMethod<[ItemKind, bigint, Principal, Permission], Share>,
  'uploadFile' : ActorMethod<
    [string, FolderId, ExternalBlob, bigint, string],
    FileEntry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];