/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FolderId = IDL.Nat;
export const Folder = IDL.Record({
  'id' : FolderId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'parentId' : IDL.Opt(FolderId),
});
export const FileId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ActivityId = IDL.Nat;
export const ActivityAction = IDL.Variant({
  'rename' : IDL.Null,
  'revoke' : IDL.Null,
  'move' : IDL.Null,
  'delete' : IDL.Null,
  'create' : IDL.Null,
  'share' : IDL.Null,
  'upload' : IDL.Null,
  'permissionChange' : IDL.Null,
});
export const ItemKind = IDL.Variant({ 'file' : IDL.Null, 'folder' : IDL.Null });
export const ActivityEntry = IDL.Record({
  'id' : ActivityId,
  'itemId' : IDL.Nat,
  'action' : ActivityAction,
  'owner' : IDL.Principal,
  'atNs' : IDL.Int,
  'itemKind' : ItemKind,
  'itemName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileEntry = IDL.Record({
  'id' : FileId,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'updatedAt' : IDL.Int,
  'folderId' : FolderId,
});
export const FolderContents = IDL.Record({
  'files' : IDL.Vec(FileEntry),
  'folders' : IDL.Vec(Folder),
});
export const ShareId = IDL.Nat;
export const Permission = IDL.Variant({
  'edit' : IDL.Null,
  'readOnly' : IDL.Null,
});
export const Share = IDL.Record({
  'id' : ShareId,
  'permission' : Permission,
  'itemId' : IDL.Nat,
  'sharedBy' : IDL.Principal,
  'createdAt' : IDL.Int,
  'sharedWith' : IDL.Principal,
  'itemKind' : ItemKind,
});
export const SearchResult = IDL.Record({
  'files' : IDL.Vec(FileEntry),
  'folders' : IDL.Vec(Folder),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
  'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEntry)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFile' : IDL.Func([FileId], [IDL.Opt(FileEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFolderContents' : IDL.Func([FolderId], [FolderContents], ['query']),
  'listShares' : IDL.Func([], [IDL.Vec(Share)], ['query']),
  'moveFolder' : IDL.Func([FolderId, IDL.Opt(FolderId)], [IDL.Opt(Folder)], []),
  'renameFolder' : IDL.Func([FolderId, IDL.Text], [IDL.Opt(Folder)], []),
  'revokeShare' : IDL.Func([ShareId], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchFiles' : IDL.Func([IDL.Text], [SearchResult], ['query']),
  'shareItem' : IDL.Func(
      [ItemKind, IDL.Nat, IDL.Principal, Permission],
      [Share],
      [],
    ),
  'uploadFile' : IDL.Func(
      [IDL.Text, FolderId, ExternalBlob, IDL.Nat, IDL.Text],
      [FileEntry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FolderId = IDL.Nat;
  const Folder = IDL.Record({
    'id' : FolderId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'parentId' : IDL.Opt(FolderId),
  });
  const FileId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ActivityId = IDL.Nat;
  const ActivityAction = IDL.Variant({
    'rename' : IDL.Null,
    'revoke' : IDL.Null,
    'move' : IDL.Null,
    'delete' : IDL.Null,
    'create' : IDL.Null,
    'share' : IDL.Null,
    'upload' : IDL.Null,
    'permissionChange' : IDL.Null,
  });
  const ItemKind = IDL.Variant({ 'file' : IDL.Null, 'folder' : IDL.Null });
  const ActivityEntry = IDL.Record({
    'id' : ActivityId,
    'itemId' : IDL.Nat,
    'action' : ActivityAction,
    'owner' : IDL.Principal,
    'atNs' : IDL.Int,
    'itemKind' : ItemKind,
    'itemName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileEntry = IDL.Record({
    'id' : FileId,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'updatedAt' : IDL.Int,
    'folderId' : FolderId,
  });
  const FolderContents = IDL.Record({
    'files' : IDL.Vec(FileEntry),
    'folders' : IDL.Vec(Folder),
  });
  const ShareId = IDL.Nat;
  const Permission = IDL.Variant({ 'edit' : IDL.Null, 'readOnly' : IDL.Null });
  const Share = IDL.Record({
    'id' : ShareId,
    'permission' : Permission,
    'itemId' : IDL.Nat,
    'sharedBy' : IDL.Principal,
    'createdAt' : IDL.Int,
    'sharedWith' : IDL.Principal,
    'itemKind' : ItemKind,
  });
  const SearchResult = IDL.Record({
    'files' : IDL.Vec(FileEntry),
    'folders' : IDL.Vec(Folder),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFolder' : IDL.Func([IDL.Text, IDL.Opt(FolderId)], [Folder], []),
    'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEntry)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFile' : IDL.Func([FileId], [IDL.Opt(FileEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFolderContents' : IDL.Func([FolderId], [FolderContents], ['query']),
    'listShares' : IDL.Func([], [IDL.Vec(Share)], ['query']),
    'moveFolder' : IDL.Func(
        [FolderId, IDL.Opt(FolderId)],
        [IDL.Opt(Folder)],
        [],
      ),
    'renameFolder' : IDL.Func([FolderId, IDL.Text], [IDL.Opt(Folder)], []),
    'revokeShare' : IDL.Func([ShareId], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchFiles' : IDL.Func([IDL.Text], [SearchResult], ['query']),
    'shareItem' : IDL.Func(
        [ItemKind, IDL.Nat, IDL.Principal, Permission],
        [Share],
        [],
      ),
    'uploadFile' : IDL.Func(
        [IDL.Text, FolderId, ExternalBlob, IDL.Nat, IDL.Text],
        [FileEntry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };